/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package principal;

import controlador.RegistroController;
import javax.swing.DefaultComboBoxModel;
import modelo.Club;

/**
 *
 * @author Alejandro Mir
 */
public class VentanaRegistro extends javax.swing.JFrame {

    /**
     * Creates new form VentanaRegistro
     */
    
    RegistroController registroController;
    
    public VentanaRegistro() {
        initComponents();
        
        registroController = new RegistroController();
        jComboBoxPronvincia.setModel(new DefaultComboBoxModel(registroController.getProvincias()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelNombreUsuario = new javax.swing.JLabel();
        jTextFieldNombreUsuario = new javax.swing.JTextField();
        jLabelClub = new javax.swing.JLabel();
        jLabelCorreo = new javax.swing.JLabel();
        jLabelContrasenya = new javax.swing.JLabel();
        jTextFieldCorreo = new javax.swing.JTextField();
        jLabelEdad = new javax.swing.JLabel();
        jComboBoxEdadDia = new javax.swing.JComboBox<>();
        jComboBoxEdadMes = new javax.swing.JComboBox<>();
        jComboBoxEdadAnyo = new javax.swing.JComboBox<>();
        jButtonOk = new javax.swing.JButton();
        jLabelCuentaBancaria = new javax.swing.JLabel();
        jTextFieldCuentaBancaria = new javax.swing.JTextField();
        jPasswordFieldContrasenya = new javax.swing.JPasswordField();
        jTextFieldNombreMenor = new javax.swing.JTextField();
        jLabelEsMenor = new javax.swing.JLabel();
        jTextFieldDniMenor = new javax.swing.JTextField();
        jComboBoxClub = new javax.swing.JComboBox<>();
        jLabelProvincia = new javax.swing.JLabel();
        jComboBoxPronvincia = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabelNombreUsuario.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelNombreUsuario.setText("Nombre de usuario:");

        jTextFieldNombreUsuario.setToolTipText("");
        jTextFieldNombreUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNombreUsuarioActionPerformed(evt);
            }
        });

        jLabelClub.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelClub.setText("Club:");

        jLabelCorreo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelCorreo.setText("Correo:");

        jLabelContrasenya.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelContrasenya.setText("Contraseña:");

        jLabelEdad.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelEdad.setText("Edad:");

        jComboBoxEdadDia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "3", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        jComboBoxEdadDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxEdadDiaActionPerformed(evt);
            }
        });

        jComboBoxEdadMes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre" }));

        jComboBoxEdadAnyo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2020", "2019", "2018", "2017", "2016", "2015", "2014", "2013", "2012", "2011", "2010", "2009", "2008", "2007", "2006", "2005", "2004", "2003", "2002", "2001", "2000", "1999", "1998", "1997", "1996", "1995", "1994", "1993", "1992", "1991", "1990", "1989", "1988", "1987", "1986", "1985", "1984", "1983", "1982", "1981", "1980", "1979", "1978", "1977", "1976", "1975", "1974", "1973", "1972", "1971", "1970", "1969", "1968", "1967" }));

        jButtonOk.setText("OK");
        jButtonOk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonOkMouseClicked(evt);
            }
        });
        jButtonOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOkActionPerformed(evt);
            }
        });

        jLabelCuentaBancaria.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelCuentaBancaria.setText("Cuenta bancaria:");

        jTextFieldCuentaBancaria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCuentaBancariaActionPerformed(evt);
            }
        });

        jTextFieldNombreMenor.setText("Nombre y apellidos");
        jTextFieldNombreMenor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNombreMenorActionPerformed(evt);
            }
        });

        jLabelEsMenor.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jLabelEsMenor.setText("Si el jugador es menor de 16 años, el responsable del jugador debe rellenar los siguientes datos: ");

        jTextFieldDniMenor.setText("DNI");
        jTextFieldDniMenor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDniMenorActionPerformed(evt);
            }
        });

        jComboBoxClub.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Club Pingüino", "Leon Club", "Tigre C.A.", "Cattaleya Dream Team", "Santoory Ajedrez" }));

        jLabelProvincia.setText("Provincia:");

        jComboBoxPronvincia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxPronvincia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxPronvinciaActionPerformed(evt);
            }
        });
        jComboBoxPronvincia.addVetoableChangeListener(new java.beans.VetoableChangeListener() {
            public void vetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {
                jComboBoxPronvinciaVetoableChange(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonOk)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldNombreUsuario)
                            .addComponent(jLabelNombreUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                            .addComponent(jLabelProvincia)
                            .addComponent(jComboBoxPronvincia, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabelEdad)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jComboBoxEdadDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jComboBoxEdadMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jComboBoxEdadAnyo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(21, 21, 21)
                                        .addComponent(jLabelCuentaBancaria))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(7, 7, 7)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabelClub)
                                            .addComponent(jComboBoxClub, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(6, 6, 6)
                                                .addComponent(jLabelCorreo))
                                            .addComponent(jTextFieldCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(339, 339, 339)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jTextFieldCuentaBancaria, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabelContrasenya)
                                        .addComponent(jPasswordFieldContrasenya, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addContainerGap(124, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelEsMenor)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jTextFieldDniMenor, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextFieldNombreMenor, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNombreUsuario)
                    .addComponent(jLabelEdad)
                    .addComponent(jLabelCuentaBancaria))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldNombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxEdadDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxEdadMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxEdadAnyo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldCuentaBancaria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelClub)
                    .addComponent(jLabelCorreo)
                    .addComponent(jLabelContrasenya)
                    .addComponent(jLabelProvincia))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPasswordFieldContrasenya, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxClub, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxPronvincia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addComponent(jLabelEsMenor, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldNombreMenor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldDniMenor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonOk)
                .addContainerGap())
        );

        jLabelEsMenor.getAccessibleContext().setAccessibleName("Si el jugador es menor de 16 años,\nel responsable del jugador debe\nrellenar los siguientes datos:");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldCuentaBancariaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCuentaBancariaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCuentaBancariaActionPerformed

    private void jButtonOkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonOkMouseClicked
        //registroController.addJugador(club, jugador);
        VentanaAdvertenciaRegistro advertenciaregistro = new VentanaAdvertenciaRegistro();
        advertenciaregistro.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonOkMouseClicked

    private void jTextFieldNombreMenorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNombreMenorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNombreMenorActionPerformed

    private void jTextFieldDniMenorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDniMenorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDniMenorActionPerformed

    private void jButtonOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonOkActionPerformed

    private void jComboBoxEdadDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxEdadDiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxEdadDiaActionPerformed

    private void jTextFieldNombreUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNombreUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNombreUsuarioActionPerformed

    private void jComboBoxPronvinciaVetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {//GEN-FIRST:event_jComboBoxPronvinciaVetoableChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxPronvinciaVetoableChange

    private void jComboBoxPronvinciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxPronvinciaActionPerformed
     
    }//GEN-LAST:event_jComboBoxPronvinciaActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonOk;
    private javax.swing.JComboBox<String> jComboBoxClub;
    private javax.swing.JComboBox<String> jComboBoxEdadAnyo;
    private javax.swing.JComboBox<String> jComboBoxEdadDia;
    private javax.swing.JComboBox<String> jComboBoxEdadMes;
    private javax.swing.JComboBox<String> jComboBoxPronvincia;
    private javax.swing.JLabel jLabelClub;
    private javax.swing.JLabel jLabelContrasenya;
    private javax.swing.JLabel jLabelCorreo;
    private javax.swing.JLabel jLabelCuentaBancaria;
    private javax.swing.JLabel jLabelEdad;
    private javax.swing.JLabel jLabelEsMenor;
    private javax.swing.JLabel jLabelNombreUsuario;
    private javax.swing.JLabel jLabelProvincia;
    private javax.swing.JPasswordField jPasswordFieldContrasenya;
    private javax.swing.JTextField jTextFieldCorreo;
    private javax.swing.JTextField jTextFieldCuentaBancaria;
    private javax.swing.JTextField jTextFieldDniMenor;
    private javax.swing.JTextField jTextFieldNombreMenor;
    private javax.swing.JTextField jTextFieldNombreUsuario;
    // End of variables declaration//GEN-END:variables
}
